### ISSUE TITLE
The script no longer works.

### ISSUE THREAD

**Issue by Remus-Catrina** [jstnryan/helium-reward-log#1]
The script no longer works.

**Comment by jstnryan** [comment]
It is functional for me. There is a small bug that causes the start month to not be auto-populated in January. Please be sure that all fields are correct before clicking "Generate Table."

If you still encounter problems, please provide more information about the problem you are having, what errors you might be seeing, and how you are trying to use the script (a screenshot of your inputs would be helpful).

**Comment by jstnryan** [comment]
Closed as stale.
