### ISSUE TITLE
Has a Helium API change stopped script working?

### ISSUE THREAD

**Issue by neildotwilliams** [jstnryan/helium-reward-log#4]
Hi, really like this script, it did the job perfectly ;-)

It seems to have stopped working for me, at least partly.   It returns some hotspot results but not all.

It says "There was a error while fetching reward info."
In the Edge Dev console (and tried on Chrome) I get:
Access to XMLHttpRequest at 'https://api.helium.io/v1/hotspots/<hotspot address>' from origin 'https://jstnryan.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If i copy/paste the links that have a CORS error directly in to my browser it opens the URL's fine.

**Comment by fastbag** [comment]
I Have the same Problem
There was a error while fetching reward info.

**Comment by jstnryan** [comment]
@fastbag @neildotwilliams Thank you both for informing me to this issue. It seems changes to the Helium API make it really adverse to being flooded with requests (and this script generates a lot of requests). I have issued an update (#5) which fixes this issue.
